use_frameworks!

platform :ios, '9.0'

target 'QingTestDemo_Example' do
  pod 'QingTestDemo', :path => '../'

  target 'QingTestDemo_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
